<?php
    define('TITULO_PAGINA', 'SII');
    define('SERVIDOR', 'http://itma2.sii/');
    define('DEP_CSS', SERVIDOR . 'public/css/');
    define('DEP_SCRIPT', SERVIDOR . 'public/js/');
    define('DEP_IMG', SERVIDOR . 'public/img/');
    define('CONTROLLER', SERVIDOR . 'controller/');
    define('LIB_JC', SERVIDOR . 'app/lib/JC/');

    define('AUDIO', SERVIDOR . 'public/files/audio/');
    define('DOC', SERVIDOR . 'public/files/doc/');
    define('PDF', SERVIDOR . 'public/files/pdf/');
    define('VIDEO', SERVIDOR . 'public/files/video/');
    define('EXCEL', SERVIDOR . 'public/files/xlsx/');
    define('CARRERA', array('SIS','GES','IND'));

    define('DIRECCION', array(

        'error' => ['url' => 'error/error404', 'titulo' => '404'],

        'publico' => [
            'pb' => ['url' => 'prueba', 'titulo' => 'publico'],
        ],

        'sesion' => [
            'login' => ['url' => 'login/login', 'titulo' => 'Login'],
            'dashboard' => ['url' => 'login/login', 'titulo' => 'Login'],
            'recuperacion' => ['url' => 'login/recup_contra', 'titulo' => 'Recuperacion de cuenta']
        ],

        'se' => [
            'perfil' => ['url' => 'usuario/informacion', 'titulo' => 'Perfil'],
            'dashboard' => ['url' => 'se/dashboard', 'titulo' => 'SII'],
            'alumnos' => ['url' => 'se/alumnos/creacion_alumnos','titulo' => 'Creacion de alumnos'],
            'listado_alumno' => ['url' => 'se/alumnos/listado_alumno','titulo' => 'Listado de alumnos'],
            'historial_academico' => ['url' => 'se/alumnos/historial_academico','titulo' => 'Historial academico'],
            'examenes'  => ['url' => 'se/alumnos/examenes','titulo' => 'Examenes'],
            'mejores_promedios' => ['url' => 'se/alumnos/mejores_promedios','titulo' => 'Mejores Promedios'],
            'kardex' => ['url' => 'se/alumnos/kardex','titulo' => 'Kardex'],
            'modificaciones_alumno' => ['url' => 'se/alumnos/modificaciones_alumno','titulo' => 'Modificaciones de alumno'],
            'datos_generales' => ['url' => 'se/alumnos/includes_modificacion_datos/datos_generales','titulo' => 'Datos generales'],
            'calificaciones_actas' => ['url' => 'se/alumnos/calificaciones_actas','titulo' => 'Calificaciones y actas'],
            'adeudos' => ['url' => 'se/alumnos/adeudos','titulo' => 'Adeudos'],
            'constancias' => ['url' => 'se/alumnos/constancias','titulo' => 'Constancias'],
            'boletas' => ['url' => 'se/semestre/boletas','titulo' => 'Boletas'],
            'ctrl' => ['url' => 'se/numeros_control/creacion_numeros_ctrl','titulo' => 'Numeros de control'],
            'listado_numeros_ctrl' => ['url' => 'se/numeros_control/listado_numeros_ctrl', 'titulo' => 'Listado numeros de control'],
            'carreras' => ['url' => 'se/carrera/carreras', 'titulo' => 'Carreras'],
            'especialidades' => ['url' => 'se/carrera/especialidades', 'titulo' => 'Especialidades'],
            'plan_curricular' => ['url' => 'se/carrera/plan_curricular', 'titulo' => 'Plan curricular'],
            'emision_certificados' => ['url' => 'se/carrera/emision_certificados', 'titulo' => 'Emisión de certificados'],
            'actas_residencias' => ['url' => 'se/carrera/actas_residencias', 'titulo' => 'Actas de residencias'],
            'materias_se' => ['url' => 'se/carrera/materias_se', 'titulo' => 'Materias'],
            'periodos' => ['url' => 'se/semestre/periodos', 'titulo' => 'Periodos'],
            'cierre_semestre' => ['url' => 'se/semestre/cierre_semestre', 'titulo' => 'Cierre de semestre'],
            'actas_calificaciones' => ['url' => 'se/semestre/actas_calificaciones', 'titulo' => 'Actas de calificaciones'],
            'actas_sin_calificar' => ['url' => 'se/consultas/actas_sin_calificar', 'titulo' => 'Actas sin calificar'],
            'consulta_grupo' => ['url' => 'se/consultas/consulta_grupo', 'titulo' => 'Consulta de grupo'],
            'bajas_temporales' => ['url' => 'se/consultas/bajas_temporales', 'titulo' => 'Bajas temporales'],
            'alumnos_egresados' => ['url' => 'se/consultas/alumnos_egresados', 'titulo' => 'Alumnos egresados'],
            'alumnos_generales' => ['url' => 'se/consultas/alumnos_generales', 'titulo' => 'Alumnos generales'],
            'alumnos_inscritos' => ['url' => 'se/consultas/alumnos_inscritos', 'titulo' => 'Alumnos inscritos'],
            'estadisticas' => ['url' => 'dep/consultas/estadisticas', 'titulo' => 'Estadísticas'],
            'autorizacion_inscripcion' => ['url' => 'se/inscripciones/autorizacion_inscripcion', 'titulo' => 'Autorizacion de inscripcion']
        ],

        'acad' => [
            'perfil' => ['url' => 'usuario/informacion', 'titulo' => 'Perfil'],
            'dashboard' => ['url' => 'acad/dashboard', 'titulo' => 'SII'],
            'aprobar_ctrl' => ['url'=>'acad/aprobar_ctrl','titulo'=>'NUMEROS DE CONTROL'],
            /* --------------------------------- RUTAS SE ---------------------------------------- */
            'dashboard_se' => ['url' => 'se/dashboard', 'titulo' => 'SII'],
            'alumnos' => ['url' => 'se/alumnos/creacion_alumnos','titulo' => 'Creacion de alumnos'],
            'listado_alumno' => ['url' => 'se/alumnos/listado_alumno','titulo' => 'Listado de alumnos'],
            'historial_academico' => ['url' => 'se/alumnos/historial_academico','titulo' => 'Historial academico'],
            'examenes'  => ['url' => 'se/alumnos/examenes','titulo' => 'Examenes'],
            'mejores_promedios' => ['url' => 'se/alumnos/mejores_promedios','titulo' => 'Mejores Promedios'],
            'kardex' => ['url' => 'se/alumnos/kardex','titulo' => 'Kardex'],
            'modificaciones_alumno' => ['url' => 'se/alumnos/modificaciones_alumno','titulo' => 'Modificaciones de alumno'],
            'datos_generales' => ['url' => 'se/alumnos/includes_modificacion_datos/datos_generales','titulo' => 'Datos generales'],
            'calificaciones_actas' => ['url' => 'se/alumnos/calificaciones_actas','titulo' => 'Calificaciones y actas'],
            'adeudos' => ['url' => 'se/alumnos/adeudos','titulo' => 'Adeudos'],
            'constancias' => ['url' => 'se/alumnos/constancias','titulo' => 'Constancias'],
            'boletas' => ['url' => 'se/semestre/boletas','titulo' => 'Boletas'],
            'ctrl' => ['url' => 'se/numeros_control/creacion_numeros_ctrl','titulo' => 'Numeros de control'],
            'listado_numeros_ctrl' => ['url' => 'se/numeros_control/listado_numeros_ctrl', 'titulo' => 'Listado numeros de control'],
            'carreras' => ['url' => 'se/carrera/carreras', 'titulo' => 'Carreras'],
            'especialidades' => ['url' => 'se/carrera/especialidades', 'titulo' => 'Especialidades'],
            'plan_curricular' => ['url' => 'se/carrera/plan_curricular', 'titulo' => 'Plan curricular'],
            'emision_certificados' => ['url' => 'se/carrera/emision_certificados', 'titulo' => 'Emisión de certificados'],
            'actas_residencias' => ['url' => 'se/carrera/actas_residencias', 'titulo' => 'Actas de residencias'],
            'materias_se' => ['url' => 'se/carrera/materias_se', 'titulo' => 'Materias'],
            'periodos' => ['url' => 'se/semestre/periodos', 'titulo' => 'Periodos'],
            'cierre_semestre' => ['url' => 'se/semestre/cierre_semestre', 'titulo' => 'Cierre de semestre'],
            'actas_calificaciones' => ['url' => 'se/semestre/actas_calificaciones', 'titulo' => 'Actas de calificaciones'],
            'actas_sin_calificar' => ['url' => 'se/consultas/actas_sin_calificar', 'titulo' => 'Actas sin calificar'],
            'consulta_grupo' => ['url' => 'se/consultas/consulta_grupo', 'titulo' => 'Consulta de grupo'],
            'bajas_temporales' => ['url' => 'se/consultas/bajas_temporales', 'titulo' => 'Bajas temporales'],
            'alumnos_egresados' => ['url' => 'se/consultas/alumnos_egresados', 'titulo' => 'Alumnos egresados'],
            'alumnos_generales' => ['url' => 'se/consultas/alumnos_generales', 'titulo' => 'Alumnos generales'],
            'alumnos_inscritos' => ['url' => 'se/consultas/alumnos_inscritos', 'titulo' => 'Alumnos inscritos'],
            'estadisticas' => ['url' => 'se/consultas/estadisticas', 'titulo' => 'Estadisticas'],
            'autorizacion_inscripcion' => ['url' => 'se/inscripciones/autorizacion_inscripcion', 'titulo' => 'Autorizacion de inscripcion'],
            /* --------------------------------- RUTAS DEP ---------------------------------------- */
            'dashboard_dep' => ['url' => 'dep/dashboard', 'titulo' => 'SII'],
            'aula_dep' => ['url'=>'dep/mantenimiento/aula','titulo'=>'Creación de aulas'],
            'crear_horario_grupo' => ['url'=>'dep/mantenimiento/crear_horario_grupo','titulo'=>'CREACIÓN DE HORARIOS Y GRUPOS'],
            'crear_grupo_paralelo' => ['url'=>'dep/mantenimiento/creacion_grupo_paralelo','titulo'=>'CREACION DE PARALELO'],
            'horario_carrera' => ['url'=> 'dep/impresion/horario_carrera', 'titulo' => 'Horario por carrera'],
            'grupos_base' => ['url' =>'dep/impresion/grupos_base', 'titulo' => 'Grupos base'],
            'actualizar_horario_grupo' => ['url' => 'dep/mantenimiento/actualizar_horario_grupo','titulo' => 'Actualizar Horario y gurpo'],
            'inscripciones_periodo' => ['url' => 'dep/inscripciones/inscripciones_periodo', 'titulo' => 'Inscripciones'],
            'verano' => ['url' => 'dep/inscripciones/verano', 'titulo' => 'Verano'],
            'autorizaciones_academicas' => ['url' => 'dep/inscripciones/autorizaciones_academicas','titulo' => 'Autorizaciones académicas'],
            'nips_alumnos' => ['url' => 'dep/inscripciones/nips_alumnos','titulo' => "NIP'S de Alumnos"],
            'ajuste_capacidad_grupos' => ['url' => 'dep/inscripciones/ajuste_capacidad_grupos', 'titulo' => 'Ajuste de Capacidad'],
            'editar_horario' => ['url' => 'dep/editar_horario', 'titulo' => 'Editar Horario'],
            'problemas_inscripcion' => ['url' => 'dep/inscripciones/problemas_inscripcion', 'titulo' => 'Problemas de inscripción'],
            'residencias' => ['url' => 'dep/inscripciones/residencias', 'titulo' => 'Residencias'],
            'lista_asistencias' => ['url' => 'dep/consultas/lista_asistencias', 'titulo' => 'Lista de asistencias'],
            'consulta_grupos' => ['url' => 'se/consultas/consulta_grupo', 'titulo' => 'Consulta de grupo'],
            'alumnos_inscritos_dep' => ['url' => 'se/consultas/alumnos_inscritos', 'titulo' => 'Alumnos inscritos'],
            'alumnos_exam_especial' => ['url' => 'dep/consultas/alumnos_exam_especial', 'titulo' => 'Alumnos en examen especial'],
            'analisis_materias' => ['url' => 'dep/consultas/analisis_materias', 'titulo' => 'Análisis de materias'],
            'estadisticas_dep' => ['url' => 'dep/consultas/estadisticas', 'titulo' => 'Estadísticas']
        ],

        'dep' => [
            'dashboard' => ['url' => 'dep/dashboard', 'titulo' => 'SII'],
            'perfil' => ['url' => 'usuario/informacion', 'titulo' => 'Perfil'],
            'aula_dep' => ['url'=>'dep/mantenimiento/aula','titulo'=>'Creación de aulas'],
            'crear_horario_grupo' => ['url'=>'dep/mantenimiento/crear_horario_grupo','titulo'=>'CREACIÓN DE HORARIOS Y GRUPOS'],
            'crear_grupo_paralelo' => ['url'=>'dep/mantenimiento/creacion_grupo_paralelo','titulo'=>'CREACION DE PARALELO'],
            'horario_carrera' => ['url'=> 'dep/impresion/horario_carrera', 'titulo' => 'Horario por carrera'],
            'grupos_base' => ['url' =>'dep/impresion/grupos_base', 'titulo' => 'Grupos base'],
            'actualizar_horario_grupo' => ['url' => 'dep/mantenimiento/actualizar_horario_grupo','titulo' => 'Actualizar Horario y gurpo'],
            'inscripciones_periodo' => ['url' => 'dep/inscripciones/inscripciones_periodo', 'titulo' => 'Inscripciones'],
            'verano' => ['url' => 'dep/inscripciones/verano', 'titulo' => 'Verano'],
            'autorizaciones_academicas' => ['url' => 'dep/inscripciones/autorizaciones_academicas','titulo' => 'Autorizaciones académicas'],
            'nips_alumnos' => ['url' => 'dep/inscripciones/nips_alumnos','titulo' => "NIP'S de Alumnos"],
            'ajuste_capacidad_grupos' => ['url' => 'dep/inscripciones/ajuste_capacidad_grupos', 'titulo' => 'Ajuste de Capacidad'],
            'editar_horario' => ['url' => 'dep/editar_horario', 'titulo' => 'Editar Horario'],
            'problemas_inscripcion' => ['url' => 'dep/inscripciones/problemas_inscripcion', 'titulo' => 'Problemas de inscripción'],
            'residencias' => ['url' => 'dep/inscripciones/residencias', 'titulo' => 'Residencias'],
            'lista_asistencias' => ['url' => 'dep/consultas/lista_asistencias', 'titulo' => 'Lista de asistencias'],
            'consulta_grupos' => ['url' => 'se/consultas/consulta_grupo', 'titulo' => 'Consulta de grupo'],
            'alumnos_inscritos_dep' => ['url' => 'se/consultas/alumnos_inscritos', 'titulo' => 'Alumnos inscritos'],
            'alumnos_exam_especial' => ['url' => 'dep/consultas/alumnos_exam_especial', 'titulo' => 'Alumnos en examen especial'],
            'analisis_materias' => ['url' => 'dep/consultas/analisis_materias', 'titulo' => 'Análisis de materias'],
            'estadisticas_dep' => ['url' => 'dep/consultas/estadisticas', 'titulo' => 'Estadísticas']
        ],

        'rh' => [
            'perfil' => ['url' => 'usuario/informacion', 'titulo' => 'Perfil'],
            'dashboard' => ['url' => 'rh/dashboard', 'titulo' => 'SII'],
            'creacion_empleado' => ['url'=>'rh/personal/creacion_empleado','titulo'=>'Creacion de empleados'],
            'modificar_eliminar_registro' => ['url'=>'rh/personal/modificar_eliminar_registro','titulo'=>'Modificar y eliminar registro'],
            'puestos' => ['url'=>'rh/personal/puestos','titulo'=>'Puestos'],
            'plazas'=> ['url'=>'rh/personal/plazas','titulo'=>'Plazas'],
            'reorganizar_clave'=> ['url'=>'rh/personal/reorganizar_clave','titulo'=>'Reorganizar clave de puestos de personal'],
            'creacion_puestos'=>['url'=> 'rh/personal/creacion_puestos', 'titulo'=>'Creacion de puestos'],
            'asignacion_nivel_puesto'=>['url'=>'rh/personal/asignacion_nivel_puesto','titulo'=>'Asignar nivel a puesto'],
            'asignacion_puestos_personal'=>['url'=>'rh/personal/asignacion_puestos_personal', 'titulo'=>'Asignacion de puestos'],
            'jefes'=>['url'=>'rh/personal/jefes','titulo'=>'Jefes'],
            'fichas_expediente'=> ['url'=>'rh/reportes_personal/fichas_expediente','titulo'=>'Ficha de expediente de empleados'],
            'plantilla_personal'=> ['url'=>'rh/reportes_personal/plantilla_personal','titulo'=>'Plantilla de personal'],
            'listado'=> ['url'=>'rh/reportes_personal/listado','titulo'=>'Listado'],
            'listado_general'=> ['url'=>'rh/reportes_personal/listado_general','titulo'=>'Listado general de personal'],
            'listado_personal_situacion'=>['url'=>'rh/reportes_personal/listado_personal_situacion','titulo'=>'Listado de personal según su situación'],
            'puesto_personal_estructura'=> ['url'=>'rh/reportes_personal/puesto_personal_estructura','titulo'=>'Puesto de personal de acuerdo a estructura'],
            'personal'=> ['url'=>'rh/reportes_personal/personal', 'titulo'=>'Personal'],
            'personal_categoria'=>['url'=>'rh/reportes_personal/personal_categoria','titulo'=>'Personal por categoría'],
            'personal_puesto'=>['url'=>'rh/reportes_personal/personal_puesto','titulo'=>'Personal por puesto'],
            'plazas_reporte'=>['url'=>'rh/reportes_personal/plazas_reporte','titulo'=>'Plazas'],
            'vigencia_periodo'=>['url'=>'rh/control_incidencias/vigencia_periodo','titulo'=>'Vigencia de periodos'],
            'reportes'=>['url'=>'rh/control_incidencias/reportes','titulo'=>'Reportes'],
            'justificacion'=>['url'=>'rh/control_incidencias/justificacion','titulo'=>'Justificacion de incidencias'],
            'incidencia'=>['url'=>'rh/control_incidencias/incidencia','titulo'=>'Consulta de incidencias'],
            'horario_departamento'=>['url'=>'rh/control_incidencias/horario_departamento','titulo'=>'Horarios por departamento'],
            'estadistica'=>['url'=>'rh/control_incidencias/estadistica','titulo'=>'Estadistica'],
            'horarios'=>['url'=>'rh/horarios/horarios','titulo'=>'Horarios'],
            'horarios_registro'=>['url'=>'rh/horarios/registro_horario','titulo'=>'Registro Horarios'],
            'listado_horario'=>['url'=>'rh/horarios/listado_horario','titulo'=>'Listado Horarios'],
            'calendario'=>['url'=>'rh/horarios/calendario','titulo'=>'Actualizar Calendario'],
        ],

        'admin' => [
            'perfil' => ['url' => 'usuario/informacion', 'titulo' => 'Perfil'],
            'dashboard' => ['url' => 'admin/dashboard', 'titulo' => 'SII'],
            'creacion_usuarios' => ['url'=>'admin/crear_usuarios','titulo'=>'Creacion de usuarios'],
            'usuarios' => ['url'=>'admin/usuarios','titulo'=>'LISTADO DE USUARIOS']
        ],

        'alumno' => [
            'perfil' => ['url' => 'usuario/informacion', 'titulo' => 'Perfil'],
            'dashboard' => ['url' => 'alumno/dashboard', 'titulo' => 'SII'],
            'solicitud_inscripcion' => ['url' => 'alumno/inscripcion_alumno/solicitud_inscripcion', 'titulo' => 'Solicitud de inscripción'],
            'seleccion_materias' => ['url' => 'alumno/inscripcion_alumno/seleccion_materias', 'titulo' => 'Selección de materias'],
            'horario_reinscripcion' => ['url' => 'alumno/inscripcion_alumno/horario_reinscripcion', 'titulo' => 'Horario de reinscripción'],
            'servicio_social' => ['url' => 'alumno/informacion_escolar/servicio_social', 'titulo' => 'Solicitud de servicio social'],
            'datos_socioeconomicos' => ['url' => 'alumno/informacion_escolar/datos_socioeconomicos','titulo' => 'Datos socioeconómicos'],
            'boletas_calificaciones' => ['url' => 'alumno/informacion_escolar/boletas_calificaciones', 'titulo' => 'Consultas de boletas'],
            'avance_reticular' => ['url' => 'alumno/informacion_escolar/avance_reticular', 'titulo' => 'Avance reticular'],
            'kardex_reticular' => ['url' => 'alumno/informacion_escolar/kardex_reticular', 'titulo' => 'Seguimiento del Alumno'],
            'horarios_alumnos' => ['url' => 'alumno/informacion_escolar/horarios_alumnos', 'titulo' => 'Horario alumno'],
            'examenes_globales_especiales' => ['url' => 'alumno/informacion_escolar/examenes_globales_especiales', 'titulo' => 'Examenes globales y especiales'],
            'calificaciones_parciales' => ['url' => 'alumno/informacion_escolar/calificaciones_parciales', 'titulo' => 'Calificaciones parciales'],
            'evaluacion_docente' => ['url' => 'alumno/informacion_escolar/evaluacion_docente', 'titulo' => 'Evaluacion Docente']
        ],
        
        'docente' => [
            'perfil' => ['url' => 'usuario/informacion', 'titulo' => 'Perfil'],
            'dashboard' => ['url' => 'docente/dashboard', 'titulo' => 'SII'],
            'horario_docente' => ['url' => 'docente/horario/horario_docente', 'titulo' => 'Horario del periodo en curso'],
            'reporte_curso' => ['url' => 'docente/documentos/reporte_curso', 'titulo' => 'Reporte de inicio de curso'],
            'calificaciones_parciales' => ['url' => 'docente/documentos/calificaciones_parciales', 'titulo' => 'Calificaciones parciales'],
            'periodo_curso' => ['url' => 'docente/grupos/periodo_curso', 'titulo' => 'Captura calificaciones'],
        ],

        'cbas' => [
            'perfil' => ['url' => 'usuario/informacion', 'titulo' => 'Perfil'],
            'dashboard' => ['url' => 'cbas/dashboard', 'titulo' => 'SII'],
            'grupos_carrera' => ['url' => 'cbas/grupos/grupos_carrera','titulo'=>'Grupos por carrera'],
            'grupos_departamento' =>['url' => 'cbas/grupos/grupos_departamento','titulo'=>'Grupos por departamento'],
            'alumnos_general' => ['url' => 'se/consultas/alumnos_generales', 'titulo' => 'Alumnos generales'],
            'alumnos_inscritos'=> ['url' => 'se/consultas/alumnos_inscritos', 'titulo' => 'Alumnos inscritos'],
            'plazas_asignadas' => ['url' => 'cbas/profesores/plazas_asignadas', 'titulo'=>'Reporte de información de personal'],
            'examenes_especiales' => ['url' => 'cbas/profesores/examenes_especiales', 'titulo' => 'Docente sin calificar examenes especiales'],
            'lista_asistencia' => ['url' => 'dep/consultas/lista_asistencias', 'titulo' => 'Lista de asistencias'],
            'estadistica_cbas' => ['url' => 'dep/consultas/estadisticas', 'titulo' => 'Estadísticas'],
            'asignacion_grupo' => ['url'=>'cbas/docentes/asignacion_grupo', 'titulo'=>'Asignaón a grupo'],
            'asig_temporal_depto' => ['url'=>'cbas/docentes/asig_temporal_depto', 'titulo'=>'Asignacón temporal a otro departamento'],
            'horarios_examenes' => ['url'=>'cbas/alumnos/horarios_examenes', 'titulo'=>'Horarios para examenes especiales o globales'],
        ],

        'sis' => [
            'perfil' => ['url' => 'usuario/informacion', 'titulo' => 'Perfil'],
            'dashboard' => ['url' => 'cbas/dashboard', 'titulo' => 'SII'],
            'grupos_carrera' => ['url' => 'cbas/grupos/grupos_carrera','titulo'=>'Grupos por carrera'],
            'grupos_departamento' =>['url' => 'cbas/grupos/grupos_departamento','titulo'=>'Grupos por departamento'],
            'alumnos_general' => ['url' => 'se/consultas/alumnos_generales', 'titulo' => 'Alumnos generales'],
            'alumnos_inscritos'=> ['url' => 'se/consultas/alumnos_inscritos', 'titulo' => 'Alumnos inscritos'],
            'plazas_asignadas' => ['url' => 'cbas/profesores/plazas_asignadas', 'titulo'=>'Reporte de información de personal'],
            'examenes_especiales' => ['url' => 'cbas/profesores/examenes_especiales', 'titulo' => 'Docente sin calificar examenes especiales'],
            'lista_asistencia' => ['url' => 'dep/consultas/lista_asistencias', 'titulo' => 'Lista de asistencias'],
            'estadistica_cbas' => ['url' => 'dep/consultas/estadisticas', 'titulo' => 'Estadísticas'],
            'asignacion_grupo' => ['url'=>'cbas/docentes/asignacion_grupo', 'titulo'=>'Asignaón a grupo'],
            'asig_temporal_depto' => ['url'=>'cbas/docentes/asig_temporal_depto', 'titulo'=>'Asignacón temporal a otro departamento'],
            'horarios_examenes' => ['url'=>'cbas/alumnos/horarios_examenes', 'titulo'=>'Horarios para examenes especiales o globales'],
        ],

        'ges' => [
            'perfil' => ['url' => 'usuario/informacion', 'titulo' => 'Perfil'],
            'dashboard' => ['url' => 'cbas/dashboard', 'titulo' => 'SII'],
            'grupos_carrera' => ['url' => 'cbas/grupos/grupos_carrera','titulo'=>'Grupos por carrera'],
            'grupos_departamento' =>['url' => 'cbas/grupos/grupos_departamento','titulo'=>'Grupos por departamento'],
            'alumnos_general' => ['url' => 'se/consultas/alumnos_generales', 'titulo' => 'Alumnos generales'],
            'alumnos_inscritos'=> ['url' => 'se/consultas/alumnos_inscritos', 'titulo' => 'Alumnos inscritos'],
            'plazas_asignadas' => ['url' => 'cbas/profesores/plazas_asignadas', 'titulo'=>'Reporte de información de personal'],
            'examenes_especiales' => ['url' => 'cbas/profesores/examenes_especiales', 'titulo' => 'Docente sin calificar examenes especiales'],
            'lista_asistencia' => ['url' => 'dep/consultas/lista_asistencias', 'titulo' => 'Lista de asistencias'],
            'estadistica_cbas' => ['url' => 'dep/consultas/estadisticas', 'titulo' => 'Estadísticas'],
            'asignacion_grupo' => ['url'=>'cbas/docentes/asignacion_grupo', 'titulo'=>'Asignaón a grupo'],
            'asig_temporal_depto' => ['url'=>'cbas/docentes/asig_temporal_depto', 'titulo'=>'Asignacón temporal a otro departamento'],
            'horarios_examenes' => ['url'=>'cbas/alumnos/horarios_examenes', 'titulo'=>'Horarios para examenes especiales o globales'],
        ],

        'ind' => [
            'perfil' => ['url' => 'usuario/informacion', 'titulo' => 'Perfil'],
            'dashboard' => ['url' => 'cbas/dashboard', 'titulo' => 'SII'],
            'grupos_carrera' => ['url' => 'cbas/grupos/grupos_carrera','titulo'=>'Grupos por carrera'],
            'grupos_departamento' =>['url' => 'cbas/grupos/grupos_departamento','titulo'=>'Grupos por departamento'],
            'alumnos_general' => ['url' => 'se/consultas/alumnos_generales', 'titulo' => 'Alumnos generales'],
            'alumnos_inscritos'=> ['url' => 'se/consultas/alumnos_inscritos', 'titulo' => 'Alumnos inscritos'],
            'plazas_asignadas' => ['url' => 'cbas/profesores/plazas_asignadas', 'titulo'=>'Reporte de información de personal'],
            'examenes_especiales' => ['url' => 'cbas/profesores/examenes_especiales', 'titulo' => 'Docente sin calificar examenes especiales'],
            'lista_asistencia' => ['url' => 'dep/consultas/lista_asistencias', 'titulo' => 'Lista de asistencias'],
            'estadistica_cbas' => ['url' => 'dep/consultas/estadisticas', 'titulo' => 'Estadísticas'],
            'asignacion_grupo' => ['url'=>'cbas/docentes/asignacion_grupo', 'titulo'=>'Asignaón a grupo'],
            'asig_temporal_depto' => ['url'=>'cbas/docentes/asig_temporal_depto', 'titulo'=>'Asignacón temporal a otro departamento'],
            'horarios_examenes' => ['url'=>'cbas/alumnos/horarios_examenes', 'titulo'=>'Horarios para examenes especiales o globales'],
        ],
        'dir' => [
            'perfil' => ['url' => 'usuario/informacion', 'titulo' => 'Perfil'],
            'dashboard' => ['url' => 'dir/dashboard', 'titulo' => 'SII'],
            'aprobar_ctrl' => ['url'=>'dir/aprobar_ctrl','titulo'=>'NUMEROS DE CONTROL'],
            /* --------------------------------- RUTAS ADMIN ---------------------------------------- */
            'dashboard_admin' => ['url' => 'admin/dashboard', 'titulo' => 'SII'],
            'creacion_usuarios' => ['url'=>'admin/crear_usuarios','titulo'=>'Creacion de usuarios'],
            'usuarios' => ['url'=>'admin/usuarios','titulo'=>'LISTADO DE USUARIOS'],
            /* --------------------------------- RUTAS SE ---------------------------------------- */
            'dashboard_se' => ['url' => 'se/dashboard', 'titulo' => 'SII'],
            'alumnos' => ['url' => 'se/alumnos/creacion_alumnos','titulo' => 'Creacion de alumnos'],
            'listado_alumno' => ['url' => 'se/alumnos/listado_alumno','titulo' => 'Listado de alumnos'],
            'historial_academico' => ['url' => 'se/alumnos/historial_academico','titulo' => 'Historial academico'],
            'examenes'  => ['url' => 'se/alumnos/examenes','titulo' => 'Examenes'],
            'mejores_promedios' => ['url' => 'se/alumnos/mejores_promedios','titulo' => 'Mejores Promedios'],
            'kardex' => ['url' => 'se/alumnos/kardex','titulo' => 'Kardex'],
            'modificaciones_alumno' => ['url' => 'se/alumnos/modificaciones_alumno','titulo' => 'Modificaciones de alumno'],
            'datos_generales' => ['url' => 'se/alumnos/includes_modificacion_datos/datos_generales','titulo' => 'Datos generales'],
            'calificaciones_actas' => ['url' => 'se/alumnos/calificaciones_actas','titulo' => 'Calificaciones y actas'],
            'adeudos' => ['url' => 'se/alumnos/adeudos','titulo' => 'Adeudos'],
            'constancias' => ['url' => 'se/alumnos/constancias','titulo' => 'Constancias'],
            'boletas' => ['url' => 'se/semestre/boletas','titulo' => 'Boletas'],
            'ctrl' => ['url' => 'se/numeros_control/creacion_numeros_ctrl','titulo' => 'Numeros de control'],
            'listado_numeros_ctrl' => ['url' => 'se/numeros_control/listado_numeros_ctrl', 'titulo' => 'Listado numeros de control'],
            'carreras' => ['url' => 'se/carrera/carreras', 'titulo' => 'Carreras'],
            'especialidades' => ['url' => 'se/carrera/especialidades', 'titulo' => 'Especialidades'],
            'plan_curricular' => ['url' => 'se/carrera/plan_curricular', 'titulo' => 'Plan curricular'],
            'emision_certificados' => ['url' => 'se/carrera/emision_certificados', 'titulo' => 'Emisión de certificados'],
            'actas_residencias' => ['url' => 'se/carrera/actas_residencias', 'titulo' => 'Actas de residencias'],
            'materias_se' => ['url' => 'se/carrera/materias_se', 'titulo' => 'Materias'],
            'periodos' => ['url' => 'se/semestre/periodos', 'titulo' => 'Periodos'],
            'cierre_semestre' => ['url' => 'se/semestre/cierre_semestre', 'titulo' => 'Cierre de semestre'],
            'actas_calificaciones' => ['url' => 'se/semestre/actas_calificaciones', 'titulo' => 'Actas de calificaciones'],
            'actas_sin_calificar' => ['url' => 'se/consultas/actas_sin_calificar', 'titulo' => 'Actas sin calificar'],
            'consulta_grupo' => ['url' => 'se/consultas/consulta_grupo', 'titulo' => 'Consulta de grupo'],
            'bajas_temporales' => ['url' => 'se/consultas/bajas_temporales', 'titulo' => 'Bajas temporales'],
            'alumnos_egresados' => ['url' => 'se/consultas/alumnos_egresados', 'titulo' => 'Alumnos egresados'],
            'alumnos_generales' => ['url' => 'se/consultas/alumnos_generales', 'titulo' => 'Alumnos generales'],
            'alumnos_inscritos' => ['url' => 'se/consultas/alumnos_inscritos', 'titulo' => 'Alumnos inscritos'],
            'estadisticas' => ['url' => 'se/consultas/estadisticas', 'titulo' => 'Estadisticas'],
            'autorizacion_inscripcion' => ['url' => 'se/inscripciones/autorizacion_inscripcion', 'titulo' => 'Autorizacion de inscripcion'],
            /* --------------------------------- RUTAS DEP ---------------------------------------- */
            'dashboard_dep' => ['url' => 'dep/dashboard', 'titulo' => 'SII'],
            'aula_dep' => ['url'=>'dep/mantenimiento/aula','titulo'=>'Creación de aulas'],
            'crear_horario_grupo' => ['url'=>'dep/mantenimiento/crear_horario_grupo','titulo'=>'CREACIÓN DE HORARIOS Y GRUPOS'],
            'crear_grupo_paralelo' => ['url'=>'dep/mantenimiento/creacion_grupo_paralelo','titulo'=>'CREACION DE PARALELO'],
            'horario_carrera' => ['url'=> 'dep/impresion/horario_carrera', 'titulo' => 'Horario por carrera'],
            'grupos_base' => ['url' =>'dep/impresion/grupos_base', 'titulo' => 'Grupos base'],
            'actualizar_horario_grupo' => ['url' => 'dep/mantenimiento/actualizar_horario_grupo','titulo' => 'Actualizar Horario y gurpo'],
            'inscripciones_periodo' => ['url' => 'dep/inscripciones/inscripciones_periodo', 'titulo' => 'Inscripciones'],
            'verano' => ['url' => 'dep/inscripciones/verano', 'titulo' => 'Verano'],
            'autorizaciones_academicas' => ['url' => 'dep/inscripciones/autorizaciones_academicas','titulo' => 'Autorizaciones académicas'],
            'nips_alumnos' => ['url' => 'dep/inscripciones/nips_alumnos','titulo' => "NIP'S de Alumnos"],
            'ajuste_capacidad_grupos' => ['url' => 'dep/inscripciones/ajuste_capacidad_grupos', 'titulo' => 'Ajuste de Capacidad'],
            'editar_horario' => ['url' => 'dep/editar_horario', 'titulo' => 'Editar Horario'],
            'problemas_inscripcion' => ['url' => 'dep/inscripciones/problemas_inscripcion', 'titulo' => 'Problemas de inscripción'],
            'residencias' => ['url' => 'dep/inscripciones/residencias', 'titulo' => 'Residencias'],
            'lista_asistencias' => ['url' => 'dep/consultas/lista_asistencias', 'titulo' => 'Lista de asistencias'],
            'consulta_grupos' => ['url' => 'se/consultas/consulta_grupo', 'titulo' => 'Consulta de grupo'],
            'alumnos_inscritos_dep' => ['url' => 'se/consultas/alumnos_inscritos', 'titulo' => 'Alumnos inscritos'],
            'alumnos_exam_especial' => ['url' => 'dep/consultas/alumnos_exam_especial', 'titulo' => 'Alumnos en examen especial'],
            'analisis_materias' => ['url' => 'dep/consultas/analisis_materias', 'titulo' => 'Análisis de materias'],
            'estadisticas_dep' => ['url' => 'dep/consultas/estadisticas', 'titulo' => 'Estadísticas'],
            /* --------------------------------- RUTAS RH ---------------------------------------- */
            'dashboard_rh' => ['url' => 'rh/dashboard', 'titulo' => 'SII'],
            'creacion_empleado' => ['url'=>'rh/personal/creacion_empleado','titulo'=>'Creacion de empleados'],
            'modificar_eliminar_registro' => ['url'=>'rh/personal/modificar_eliminar_registro','titulo'=>'Modificar y eliminar registro'],
            'puestos' => ['url'=>'rh/personal/puestos','titulo'=>'Puestos'],
            'plazas'=> ['url'=>'rh/personal/plazas','titulo'=>'Plazas'],
            'reorganizar_clave'=> ['url'=>'rh/personal/reorganizar_clave','titulo'=>'Reorganizar clave de puestos de personal'],
            'creacion_puestos'=>['url'=> 'rh/personal/creacion_puestos', 'titulo'=>'Creacion de puestos'],
            'asignacion_nivel_puesto'=>['url'=>'rh/personal/asignacion_nivel_puesto','titulo'=>'Asignar nivel a puesto'],
            'asignacion_puestos_personal'=>['url'=>'rh/personal/asignacion_puestos_personal', 'titulo'=>'Asignacion de puestos'],
            'jefes'=>['url'=>'rh/personal/jefes','titulo'=>'Jefes'],
            'fichas_expediente'=> ['url'=>'rh/reportes_personal/fichas_expediente','titulo'=>'Ficha de expediente de empleados'],
            'plantilla_personal'=> ['url'=>'rh/reportes_personal/plantilla_personal','titulo'=>'Plantilla de personal'],
            'listado'=> ['url'=>'rh/reportes_personal/listado','titulo'=>'Listado'],
            'listado_general'=> ['url'=>'rh/reportes_personal/listado_general','titulo'=>'Listado general de personal'],
            'listado_personal_situacion'=>['url'=>'rh/reportes_personal/listado_personal_situacion','titulo'=>'Listado de personal según su situación'],
            'puesto_personal_estructura'=> ['url'=>'rh/reportes_personal/puesto_personal_estructura','titulo'=>'Puesto de personal de acuerdo a estructura'],
            'personal'=> ['url'=>'rh/reportes_personal/personal', 'titulo'=>'Personal'],
            'personal_categoria'=>['url'=>'rh/reportes_personal/personal_categoria','titulo'=>'Personal por categoría'],
            'personal_puesto'=>['url'=>'rh/reportes_personal/personal_puesto','titulo'=>'Personal por puesto'],
            'plazas_reporte'=>['url'=>'rh/reportes_personal/plazas_reporte','titulo'=>'Plazas'],
            'vigencia_periodo'=>['url'=>'rh/control_incidencias/vigencia_periodo','titulo'=>'Vigencia de periodos'],
            'reportes'=>['url'=>'rh/control_incidencias/reportes','titulo'=>'Reportes'],
            'justificacion'=>['url'=>'rh/control_incidencias/justificacion','titulo'=>'Justificacion de incidencias'],
            'incidencia'=>['url'=>'rh/control_incidencias/incidencia','titulo'=>'Consulta de incidencias'],
            'horario_departamento'=>['url'=>'rh/control_incidencias/horario_departamento','titulo'=>'Horarios por departamento'],
            'estadistica'=>['url'=>'rh/control_incidencias/estadistica','titulo'=>'Estadistica'],
            /* --------------------------------- RUTAS DEPARTAMENTO ---------------------------------------- */
            'dashboard_departamento' => ['url' => 'cbas/dashboard', 'titulo' => 'SII'],
            'grupos_carrera' => ['url' => 'cbas/grupos/grupos_carrera','titulo'=>'Grupos por carrera'],
            'grupos_departamento' =>['url' => 'cbas/grupos/grupos_departamento','titulo'=>'Grupos por departamento'],
            'alumnos_general' => ['url' => 'se/consultas/alumnos_generales', 'titulo' => 'Alumnos generales'],
            'alumnos_inscritos'=> ['url' => 'se/consultas/alumnos_inscritos', 'titulo' => 'Alumnos inscritos'],
            'plazas_asignadas' => ['url' => 'cbas/profesores/plazas_asignadas', 'titulo'=>'Reporte de información de personal'],
            'examenes_especiales' => ['url' => 'cbas/profesores/examenes_especiales', 'titulo' => 'Docente sin calificar examenes especiales'],
            'lista_asistencia' => ['url' => 'dep/consultas/lista_asistencias', 'titulo' => 'Lista de asistencias'],
            'estadistica_cbas' => ['url' => 'dep/consultas/estadisticas', 'titulo' => 'Estadísticas'],
            'asignacion_grupo' => ['url'=>'cbas/docentes/asignacion_grupo', 'titulo'=>'Asignaón a grupo'],
            'asig_temporal_depto' => ['url'=>'cbas/docentes/asig_temporal_depto', 'titulo'=>'Asignacón temporal a otro departamento'],
            'horarios_examenes' => ['url'=>'cbas/alumnos/horarios_examenes', 'titulo'=>'Horarios para examenes especiales o globales'],
        ],
    ));
?>